site_name: Dj-Stripe
site_url: https://dj-stripe.github.io/dj-stripe/
site_description: Stripe Made Easy for Django Developers
site_footer: The link between your Django project and stripe.
site_author: Dj-Stripe Team

copyright: Copyright © 2022. All Rights Reserved.

repo_name: dj-stripe
repo_url: https://github.com/dj-stripe/dj-stripe/

theme:
  logo: assets/logo.svg
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  font:
    text: Helvetica
  name: material
  custom_dir: overrides
  static_templates:
    - 404.html
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.tabs
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)" # 
      scheme: light
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" # 
      scheme: dark
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  
      
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.extra
  - meta

plugins:
  - search
  - autorefs

nav:
  - Documentation: 
    - Getting Started:
      - Installation: installation.md
      - Managing Stripe API Keys: api_keys.md
      - A note on Stripe API Versions: api_versions.md
      - Integrating Stripe Elements: stripe_elements_js.md
    - Usage:
      - Using Stripe Webhooks: usage/webhooks.md
      - Subscribing a customer to a plan: usage/subscribing_customers.md
      - Managing subscriptions and payment sources: usage/managing_subscriptions.md
      - Manually syncing data with Stripe: usage/manually_syncing_with_stripe.md
      - Creating individual charges: usage/creating_individual_charges.md
      - Creating Usage Records: usage/creating_usage_record.md
      - Using Stripe Checkout: usage/using_stripe_checkout.md
      - Using with Docker: usage/using_with_docker.md
    - Project:
      - Contributing: project/contributing.md
      - Test Fixtures: project/test_fixtures.md
      - Credits: project/authors.md
      - Support: project/support.md
      - Release Process: project/release_process.md
    - Reference:
      - Context Managers: reference/context_managers.md
      - Enumerations: reference/enums.md
      - Managers: reference/managers.md
      - Models: reference/models.md
      - Settings: reference/settings.md
      - Utilities: reference/utils.md
  - Sponsors: 
    - Our Sponsors: project/sponsors.md
  - History:
    - dj-stripe 2.5 release notes: history/2_5_0.md
    - dj-stripe 2.4.1 release notes: history/2_4_x.md
    - dj-stripe 2.4 release notes: history/2_4_0.md
    - dj-stripe 2.0 ~ 2.3 release notes: history/2_x.md
    - dj-stripe 1.x release notes: history/1_x.md
    - dj-stripe 0.x release notes: history/0_x.md
